/// <reference types="next" />
/// <reference types="next/image-types/global" />

// This file is generated by Next.js in a normal install, but is checked in so
// the scaffold type-checks once dependencies are installed.
